# Generated by Django 5.2.7 on 2025-10-26 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-date_added'], 'verbose_name_plural': 'Cars'},
        ),
        migrations.RemoveField(
            model_name='cartype',
            name='description',
        ),
        migrations.AlterModelTable(
            name='car',
            table='cars',
        ),
    ]
