# Generated by Django 5.2.7 on 2025-10-27 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_options_remove_cartype_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_capacity',
            field=models.CharField(choices=[('2', 2), ('4', 4), ('5', 5), ('7', 7), ('8 and more', 8)], default='5', max_length=15),
        ),
        migrations.AddField(
            model_name='car',
            name='location',
            field=models.CharField(choices=[('Tbilisi', 'tbilisi'), ('Kutaisi', 'kutaisi'), ('Batumi', 'batumi'), ('Rustavi', 'rustavi'), ('Dmanisi', 'dmanisi')], default='Tbilisi', max_length=10),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual'), ('CVT', 'cvt')], default='Automatic', max_length=10),
        ),
        migrations.AlterField(
            model_name='carrental',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental', to=settings.AUTH_USER_MODEL),
        ),
    ]
