# Generated by Django 5.2.7 on 2025-10-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_car_capacity_car_location_car_transmission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='location',
            field=models.CharField(choices=[('Tbilisi', 'Tbilisi'), ('Kutaisi', 'Kutaisi'), ('Batumi', 'Batumi'), ('Rustavi', 'Rustavi'), ('Dmanisi', 'Dmanisi')], default='Tbilisi', max_length=10),
        ),
    ]
