# Generated by Django 5.2.7 on 2025-10-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_car_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_make',
            field=models.CharField(choices=[('toyota', 'Toyota'), ('honda', 'Honda'), ('ford', 'Ford'), ('chevrolet', 'Chevrolet'), ('nissan', 'Nissan'), ('volkswagen', 'Volkswagen'), ('bmw', 'BMW'), ('mercedes', 'Mercedes-Benz'), ('audi', 'Audi'), ('hyundai', 'Hyundai'), ('kia', 'Kia'), ('mazda', 'Mazda'), ('subaru', 'Subaru'), ('tesla', 'Tesla'), ('jeep', 'Jeep'), ('land_rover', 'Land Rover'), ('volvo', 'Volvo'), ('porsche', 'Porsche'), ('lexus', 'Lexus'), ('rolls-royce', 'Rolls-Royce')], default='Car Make', max_length=20),
        ),
    ]
