# Generated by Django 5.2.7 on 2025-10-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_alter_car_car_make'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_make',
            field=models.CharField(choices=[('toyota', 'Toyota'), ('honda', 'Honda'), ('ford', 'Ford'), ('chevrolet', 'Chevrolet'), ('Nissan', 'nissan'), ('volkswagen', 'Volkswagen'), ('bmw', 'BMW'), ('mercedes', 'Mercedes-Benz'), ('Audi', 'Audi'), ('hyundai', 'Hyundai'), ('kia', 'Kia'), ('mazda', 'Mazda'), ('subaru', 'Subaru'), ('tesla', 'Tesla'), ('jeep', 'Jeep'), ('land_rover', 'Land Rover'), ('volvo', 'Volvo'), ('Porsche', 'porsche'), ('Lexus', 'lexus'), ('rolls-royce', 'Rolls-Royce')], max_length=20),
        ),
    ]
